# Generated by Django 5.1.7 on 2025-07-22 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="sender",
        ),
    ]
